version: "3"
services:
  web:
    container_name: port_error_check
    restart: always
    environment:
      - SWITCHIPLIST=${SWITCHIPLIST}
      - USERNAME=${USERNAME}
      - PASSWORD=${PASSWORD}

    volumes:
      - /usr/src/app
    command: python main.py
    build:
      context: .
